Repository sendgrid/sendgrid-python, pull requests merged in 2018-06, with the labels that each got.

#581 fixing link to use cases readme
  README.md
  TROUBLESHOOTING.md
Labels: status: code review request

#513 update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: code review request, type: bug, type: docs update

#537 Add unittesting support to .codeclimate.yml
  .travis.yml
Labels: difficulty: easy, hacktoberfest, status: code review request, type: sendgrid enhancement

#538 Fix bug in get_mock_personalization_dict()
  examples/helpers/mail/mail_example.py
Labels: difficulty: easy, status: code review request, type: bug, type: docs update

#554 Ensure params are applied independently
  sendgrid/helpers/mail/mail.py
Labels: difficulty: medium, status: code review request, type: community enhancement

#557 Client cleanup
  LICENSE.txt
  sendgrid/sendgrid.py
  test/test_sendgrid.py
Labels: difficulty: medium, status: code review request, type: community enhancement

#570 Make Mail helper parameters truly optional
  sendgrid/helpers/mail/mail.py
Labels: status: code review request

#573 Add link to additional resource
  USE_CASES.md
Labels: status: code review request

#585 Updated def build_personalization
  examples/helpers/mail/mail_example.py
Labels: status: code review request

#583 Fix `Personalization.substitutions` setter
  sendgrid/helpers/mail/personalization.py
  test/test_mail.py
Labels: status: code review request
