Repository sendgrid/sendgrid-python, pull requests merged in 2018-08, with the labels that each got.

#599 Updated README for more info
  README.md
Labels: difficulty: easy, status: code review request, type: sendgrid enhancement

#600 readme tag update
  README.md
Labels: difficulty: easy, status: code review request, type: docs update

#588 Update Readme
  README.md
Labels: difficulty: easy, status: ready for deploy, type: docs update

#603 update TROUBLESHOOTING.md to link to correct use cases page
  TROUBLESHOOTING.md
Labels: status: ready for deploy, type: docs update

#601 Minor readability update
  CONTRIBUTING.md
Labels: status: ready for deploy, type: docs update

#478 Add slack event integration
  use_cases/README.md
  use_cases/slack_event_api_integration.md
Labels: difficulty: medium, hacktoberfest, status: ready for deploy, type: sendgrid enhancement

#408 Add stats helper
  examples/helpers/stats/stats_example.py
  sendgrid/helpers/stats/README.md
  sendgrid/helpers/stats/__init__.py
  sendgrid/helpers/stats/stats.py
  test/test_stats.py
Labels: difficulty: medium, hacktoberfest, status: ready for deploy, type: sendgrid enhancement

#443 Add a tutorial to deploy a simple "Hello Email" app on Heroku
  use_cases/README.md
  use_cases/flask_heroku.md
Labels: difficulty: medium, hacktoberfest, status: ready for deploy, type: docs update

#595 Issue #587 Change type of category in Mail.add_category from string to Category
  sendgrid/helpers/mail/mail.py
Labels: difficulty: easy, status: ready for deploy, type: community enhancement

#598 Update TROUBLESHOOTING.md
  TROUBLESHOOTING.md
Labels: difficulty: easy, status: ready for deploy, type: docs update

#604 Issue #547: Added comment for attachments to be base64 encoded #patch
  examples/helpers/mail/mail_example.py
Labels: status: code review request

#596 #Issue584 Fix docker build
  docker/Dockerfile
Labels: difficulty: easy, status: ready for deploy, type: community enhancement
