Repository sendgrid/sendgrid-python, pull requests merged in 2018-05, with the labels that each got.

#414 Provide utf-8 as encoding explicitly when opening text files
  register.py
  sendgrid/helpers/inbound/send.py
  sendgrid/helpers/mail/asm.py
  setup.py
Labels: difficulty: medium, hacktoberfest, status: code review request, type: bug

#424 Update Contributing.md
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: code review request, type: community enhancement

#454 Fixes Issue 451
  sendgrid/helpers/mail/mail.py
  test/test_mail.py
Labels: difficulty: medium, hacktoberfest, status: code review request, type: community enhancement

#466 Fixed PEP8 issues except E501.
  examples/accesssettings/accesssettings.py
  examples/alerts/alerts.py
  examples/apikeys/apikeys.py
  examples/asm/asm.py
  examples/browsers/browsers.py
  examples/campaigns/campaigns.py
  examples/categories/categories.py
  examples/clients/clients.py
  examples/contactdb/contactdb.py
  examples/devices/devices.py
  examples/geo/geo.py
  examples/helpers/mail/mail_example.py
  examples/ips/ips.py
  examples/mail/mail.py
  examples/mailboxproviders/mailboxproviders.py
  examples/mailsettings/mailsettings.py
  examples/partnersettings/partnersettings.py
  examples/scopes/scopes.py
  examples/senders/senders.py
  examples/stats/stats.py
  examples/subusers/subusers.py
  examples/suppression/suppression.py
  examples/templates/templates.py
  examples/trackingsettings/trackingsettings.py
  examples/user/user.py
  examples/whitelabel/whitelabel.py
  sendgrid/helpers/inbound/config.py
  sendgrid/helpers/inbound/parse.py
  sendgrid/helpers/inbound/send.py
  sendgrid/helpers/mail/mail.py
  test/test_email.py
  test/test_mail.py
  test/test_sendgrid.py
Labels: difficulty: easy, hacktoberfest, status: code review request, type: sendgrid enhancement

#514 Fix method_complexity issue in sendgrid/helpers/mail/ganalytics.py Fixes #498
  sendgrid/helpers/mail/ganalytics.py
Labels: difficulty: medium, hacktoberfest, status: code review request, type: sendgrid enhancement

#515 Updated USAGE.md and CONTRIBUTING.md
  CONTRIBUTING.md
  USAGE.md
Labels: difficulty: easy, hacktoberfest, status: code review request, type: bug, type: docs update

#519 Corrected grammatical error in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: code review request, type: bug, type: docs update

#529 Create a Use Cases Directory
  USE_CASES.md
  use_cases/README.md
  use_cases/asynchronous_mail_send.md
  use_cases/attachment.md
  use_cases/domain_whitelabel.md
  use_cases/email_stats.md
  use_cases/error_handling.md
  use_cases/transational_templates.md
Labels: difficulty: easy, hacktoberfest, status: code review request, type: sendgrid enhancement
