Repository sendgrid/sendgrid-python, pull requests merged in 2018-10, with the labels that each got.

#611 fixes #610
  README.md
Labels: difficulty: easy, status: cla not signed, type: docs update

#616 Fix typos
  .github/PULL_REQUEST_TEMPLATE
  CONTRIBUTING.md
  README.md
  sendgrid/__init__.py
  sendgrid/helpers/endpoints/ip/unassigned.py
  sendgrid/sendgrid.py
  use_cases/aws.md
  use_cases/slack_event_api_integration.md
  use_cases/transational_templates.md
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#619 Fix format of dependency `pytest`
  requirements.txt
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: bug

#626 v4: Drop support for EOL Python 2.6 and 3.0-3.3
  .travis.yml
  CONTRIBUTING.md
  README.md
  docker/Dockerfile
  sendgrid/helpers/inbound/send.py
  sendgrid/helpers/mail/content.py
  sendgrid/helpers/mail/exceptions.py
  sendgrid/helpers/mail/from_email.py
  sendgrid/helpers/mail/html_content.py
  sendgrid/helpers/mail/mail.py
  sendgrid/helpers/mail/plain_text_content.py
  sendgrid/helpers/mail/to_email.py
  sendgrid/helpers/mail/validators.py
  sendgrid/sendgrid.py
  setup.py
  test/test_app.py
  test/test_config.py
  test/test_email.py
  test/test_mail.py
  test/test_parse.py
  test/test_project.py
  test/test_send.py
  test/test_sendgrid.py
  tox.ini
  use_cases/aws.md
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#618 Quote names containing comma or semicolon
  sendgrid/helpers/mail/email.py
  test/test_email.py
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement

#630 Update requirements.txt
  requirements.txt
Labels: difficulty: easy, status: code review request, type: community enhancement

#636 Fix broken link for mail example
  sendgrid/helpers/mail/README.md
Labels: difficulty: easy, hacktoberfest, status: ready for deploy, type: docs update

#656 Fix helper mail_example redirection link
  README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#637 v4: Add support for Python 3.7
  .travis.yml
  setup.py
  tox.ini
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#692 Add unit tests for spam check
  test/test_spam_check.py
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#690 #671: corrected links in CoC. Hacktoberfest.
  CODE_OF_CONDUCT.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy

#687 Remove references to "Whitelabel"
  USAGE.md
  examples/senderauthentication/senderauthentication.py
  use_cases/README.md
  use_cases/domain_authentication.md
  use_cases/domain_whitelabel.md
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#638 Fixed syntax errors in Kitchen sink Python example code
  proposals/mail-helper-refactor.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: bug

#663 converted README to reStructuredText and version as plain text file
  .gitignore
  .travis.yml
  MANIFEST.in
  README.md
  README.rst
  VERSION.txt
  register.py
  sendgrid/__init__.py
  sendgrid/sendgrid.py
  sendgrid/version.py
  setup.py
  test/test_project.py
  test/test_sendgrid.py
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: work in progress, type: community enhancement

#697 PEP8 Fixes and String Formatting Enhancement
  examples/helpers/stats/stats_example.py
  register.py
  sendgrid/helpers/inbound/config.py
  sendgrid/helpers/inbound/send.py
  sendgrid/helpers/mail/content.py
  sendgrid/helpers/mail/exceptions.py
  sendgrid/helpers/mail/validators.py
  setup.py
  test/test_app.py
  test/test_config.py
  test/test_mail.py
  test/test_project.py
  test/test_send.py
  test/test_sendgrid.py
  test/test_unassigned.py
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement

#683 Create README.md
  examples/helpers/README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: work in progress, type: docs update

#640 fixed changes suggested by grammarly
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  TROUBLESHOOTING.md
  USAGE.md
  docker-test/README.md
  docker/USAGE.md
  proposals/mail-helper-refactor.md
  sendgrid/helpers/inbound/README.md
  use_cases/asynchronous_mail_send.md
  use_cases/aws.md
  use_cases/django.md
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: work in progress

#631 Allow creation of Mail from EmailMessage
  sendgrid/helpers/mail/mail.py
  test/test_mail.py
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: work in progress, type: community enhancement

#715 Correct attribution links formating
  CODE_OF_CONDUCT.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: work in progress, type: docs update

#727 v4: Use raw-string notation for regex to avoid invalid escape sequence
  sendgrid/helpers/mail/validators.py
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#709 Cleanup Env Documentation
  .gitignore
  CONTRIBUTING.md
  docker/USAGE.md
  sendgrid.env
  use_cases/aws.md
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: work in progress, type: docs update

#711 Cleanup Dockerfile's
  docker-test/Dockerfile
  docker-test/entrypoint.sh
  docker/Dockerfile
  docker/entrypoint.sh
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement
