Repository sendgrid/sendgrid-python, pull requests merged in 2019-04, with the labels that each got.

#792 Fix #790
  sendgrid/helpers/mail/email.py
  test/test_email.py
Labels: difficulty: medium, status: code review request, type: bug

#797 API Key typo
  use_cases/aws.md
  use_cases/error_handling.md
Labels: difficulty: easy, status: code review request, status: ready for merge, type: docs update

#794 Update type requirements used for multiple objects.
  sendgrid/helpers/mail/footer_settings.py
  sendgrid/helpers/mail/open_tracking.py
  sendgrid/helpers/mail/subscription_tracking.py
Labels: difficulty: easy, status: code review request, type: docs update
