Repository sendgrid/sendgrid-python, pull requests merged in 2020-03, with the labels that each got.

#731 chore: Remove unused Python json modules
  examples/accesssettings/accesssettings.py
  examples/alerts/alerts.py
  examples/apikeys/apikeys.py
  examples/asm/asm.py
  examples/browsers/browsers.py
  examples/campaigns/campaigns.py
  examples/categories/categories.py
  examples/clients/clients.py
  examples/contactdb/contactdb.py
  examples/devices/devices.py
  examples/geo/geo.py
  examples/ips/ips.py
  examples/mail/mail.py
  examples/mailboxproviders/mailboxproviders.py
  examples/mailsettings/mailsettings.py
  examples/partnersettings/partnersettings.py
  examples/scopes/scopes.py
  examples/senders/senders.py
  examples/stats/stats.py
  examples/subusers/subusers.py
  examples/suppression/suppression.py
  examples/templates/templates.py
  examples/trackingsettings/trackingsettings.py
  examples/user/user.py
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved

#682 Updated link to direct to #L9
  README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: waiting for feedback, type: docs update

#706 docs: Fix grammatical errors
  examples/helpers/stats/stats_example.py
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: waiting for feedback, type: docs update

#669 docs: Fixed links in examples
  sendgrid/helpers/mail/README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: waiting for feedback, type: docs update

#714 docs: Give preference to 'to' after visible
  USAGE.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: waiting for feedback, type: docs update

#739 feat: Add equality to Email
  sendgrid/helpers/mail/email.py
  test/test_email.py
Labels: status: code review request

#734 docs: Further Remove "Whitelabel" References
  USAGE.md
Labels: status: code review request

#878 docs: fix code snippet in README
  README.md
Labels: status: code review request

#880 docs: support verbiage for login issues
  TROUBLESHOOTING.md
Labels: status: code review request
